name: Unity Tests

on:
  push:
    branches:
      - main
      - develop
      - tests-framework
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          unityVersion: 6000.3.9f1
          customParameters: >
            -executeMethod CITestRunner.RunTests
            -testRegistration Assets/Tests/test_registration.json
            -outputDir TestResults
            -tags smoke

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: TestResults
          path: TestResults/
